### ISSUE TITLE
Cleanup Tasks

### ISSUE THREAD

**Issue by RohanNagar** [RohanNagar/thunder#232]
**Description**

- [x] Fix the issues listed at: https://codeclimate.com/github/RohanNagar/thunder
- [x] Fix the issues listed at: https://lgtm.com/projects/g/RohanNagar/thunder/alerts/?mode=list
- [x] Clean up log lines
- [x] Clean up all hardcoded Strings
- [ ] Clean up scripts directory
- [ ] Clean up docs
- [ ] Migrate to the official dynamodb-local Docker image: https://hub.docker.com/r/amazon/dynamodb-local
- [x] Add integration tests for metrics (Admin port `/metrics`)
- [x] Cleanup `Configuration` classes
- [ ] Check on `disabled` tests
- [x] Add unit tests or integration tests for Swagger generation
- [x] Update Checkstyle DTD locations according to https://github.com/checkstyle/checkstyle/issues/6478
- [x] Add checkstyle checks: https://github.com/checkstyle/checkstyle/issues/6773 https://github.com/checkstyle/checkstyle/issues/6774
- [x] Fix Java client issue where the endpoint is required to end in `/` and add tests for this
- [x] Add checkstyle check https://github.com/checkstyle/checkstyle/issues/6649
- [x] Replace `run-thunder-command` with `swagger-ui` and documentation on how to use it
- [x] Update the requirements file in `docs` with Github Action: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
- [x] Checkstyle check https://github.com/checkstyle/checkstyle/issues/7183

**Comment by RohanNagar** [comment]
Todo:

- [ ] Fix insecure hash in the `run-thunder-command` script

**Comment by RohanNagar** [comment]
Moving this to v2.2 as it is not needed to block v2.1

**Comment by RohanNagar** [comment]
```yaml
name: Java CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install npm packages
      run: npm --prefix scripts/ install
    - name: Lint Node.js code
      run: npm --prefix scripts/ run lint
    - name: Shellcheck
      run: shellcheck scripts/**/*.sh
    
  build:
    runs-on: ubuntu-latest
    
    env:
      # Dummy keys to use the AWS SDK
      AWS_ACCESS_KEY_ID: 1234567890
      AWS_SECRET_ACCESS_KEY: 1234567890

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install npm packages
      run: npm --prefix scripts/ install

    - name: Build with Maven
      run: mvn package jacoco:report

    - name: Run itegration tests
      run: sh -c scripts/tools/integration-tests.sh

    - name: Docker compose integration test
      run: ./scripts/ci/docker-integration-tests.sh general

**Comment by RohanNagar** [comment]
Another task: Use enhanced DynamoDB client? https://aws.amazon.com/blogs/developer/introducing-enhanced-dynamodb-client-in-the-aws-sdk-for-java-v2/

**Comment by RohanNagar** [comment]
Update https://github.com/peter-evans/create-pull-request GH Action version

**Comment by RohanNagar** [comment]
Investigate: https://pitest.org
